---
title: "How to ggplot2"
author: "Lennart Oelschl&auml;ger"
date: '`r format(Sys.Date())`'
output: 
  slidy_presentation:
    highlight: default
    # footer: ""
    # duration: 60
---
  
## Why and what 

Welcome to this tiny course on data visualization in R with ggplot2! `r emo::ji("wave")`

### Why do we care?

Potentially, plots can [beautifully inform](https://en.wikipedia.org/wiki/Charles_Joseph_Minard#The_map_of_Napoleon's_Russian_campaign) or [horribly mislead](https://en.wikipedia.org/wiki/Misleading_graph#Truncated_graph). [Colors](https://michaelbach.de/ot) and [shape](http://vis.stanford.edu/files/2010-MTurk-CHI.pdf) matter! `r emo::ji("balance_scale")`

### Why ggplot2?

The ggplot2 package implements a grammar of graphics: Breaking up a task of making a graphic into a series of distinct tasks.

### What is this course about?

Being in "full" control of ggplot2 to produce beautiful and meaningful plots.

### What is this course *not* about?

Producing general rules about good visualization.

### Requirements

- Some R skills
- Most recent version of R
- Optionally RStudio
- Install tidyverse

### Reference

- Wickham 2016
- Tufte (1983): The Visual Display of Quantitative Information
- Wilkinson 2005
- Precessors Jonas and Hannah

### Found Errors? Have suggestions?

Please leave a note on GitHub.

## A plot

```{r}
plot(cars, main = "cars")
```

## Conclusion

Text
