name: Package update
on: [push]

jobs:
  R-CMD-check:
    name: R CMD check for ${{ matrix.config.os }} (${{ matrix.config.r }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck
      - uses: r-lib/actions/check-r-package@v2
      
  render-slides:
    name: Render slides
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Set RENV_PATHS_ROOT
        run: |
          echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV
        shell: bash
      - name: Install and activate renv
        run: |
          install.packages("renv")
          renv::activate()
        shell: Rscript {0}
      - name: Get R and OS version
        id: get-version
        run: |
          cat("##[set-output name=os-version;]", sessionInfo()$running, "\n", sep = "")
          cat("##[set-output name=r-version;]", R.Version()$version.string, sep = "")
        shell: Rscript {0}
      - name: Restore Renv package cache
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{ inputs.cache-version }}-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-
      - name: Install self
        run: |
          remotes::install_github("loelschlaeger/rcourse", upgrade = "never")
        shell: Rscript {0}
      - name: Render slides
        run: | 
          rmarkdown::render("inst/slides_data_manipulation.Rmd")
          rmarkdown::render("inst/slides_data_visualization.Rmd")
          rmarkdown::render("inst/slides_good_practices.Rmd")
        shell: Rscript {0}
          
  build-binary:
    name: Build binary package
    runs-on: windows-latest
    needs: [R-CMD-check, render-slides]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
      - name: Build binary
        run: |
          devtools::build(
            binary = TRUE,
            path = "./rcourse.zip"
          )
        shell: Rscript {0}
          
  commit-update:
    name: Commit and push update
    runs-on: windows-latest
    needs: [render-slides, build-binary]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Commit and push update
        run: |
          git config --local user.email "oelschlaeger.lennart@gmail.com"
          git config --local user.name "Lennart Oelschlaeger"
          git add "inst/*.html"
          git add "rcourse.zip"
          git commit -m "Automatic package update :construction_worker:"
          git push origin 
      
